---
- name: Check if OpenTofu is already installed
  command: tofu --version
  register: tofu_check
  failed_when: false
  changed_when: false

- name: Install OpenTofu using official installer (Debian/Ubuntu)
  block:
    - name: Download OpenTofu installer script
      get_url:
        url: https://get.opentofu.org/install-opentofu.sh
        dest: /tmp/install-opentofu.sh
        mode: '0755'
        force: yes

    - name: Run OpenTofu installer (deb method)
      command: /tmp/install-opentofu.sh --install-method deb
      args:
        creates: /usr/local/bin/tofu
      become: yes

    - name: Remove installer script
      file:
        path: /tmp/install-opentofu.sh
        state: absent
  when: 
    - ansible_os_family == 'Debian'
    - tofu_check.rc != 0

- name: Install OpenTofu using official installer (RedHat/CentOS/Fedora)
  block:
    - name: Download OpenTofu installer script
      get_url:
        url: https://get.opentofu.org/install-opentofu.sh
        dest: /tmp/install-opentofu.sh
        mode: '0755'
        force: yes

    - name: Run OpenTofu installer (rpm method)
      command: /tmp/install-opentofu.sh --install-method rpm
      args:
        creates: /usr/local/bin/tofu
      become: yes

    - name: Remove installer script
      file:
        path: /tmp/install-opentofu.sh
        state: absent
  when: 
    - ansible_os_family == 'RedHat'
    - tofu_check.rc != 0

- name: Install OpenTofu using official installer (Arch Linux)
  block:
    - name: Download OpenTofu installer script
      get_url:
        url: https://get.opentofu.org/install-opentofu.sh
        dest: /tmp/install-opentofu.sh
        mode: '0755'
        force: yes

    - name: Run OpenTofu installer (standalone method for Arch)
      command: /tmp/install-opentofu.sh --install-method standalone
      args:
        creates: /usr/local/bin/tofu
      become: yes

    - name: Remove installer script
      file:
        path: /tmp/install-opentofu.sh
        state: absent
  when: 
    - ansible_os_family == 'Archlinux'
    - tofu_check.rc != 0

- name: Ensure OpenTofu binary is executable
  file:
    path: /usr/local/bin/tofu
    mode: '0755'
  become: yes