---
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Get real user information
  set_fact:
    real_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
    real_user_home: "{{ lookup('env', 'HOME') if ansible_env.SUDO_USER is not defined else '/home/' + ansible_env.SUDO_USER }}"
  when: ansible_os_family != 'Darwin'

- name: Get real user information (macOS)
  set_fact:
    real_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
    real_user_home: "{{ lookup('env', 'HOME') if ansible_env.SUDO_USER is not defined else '/Users/' + ansible_env.SUDO_USER }}"
  when: ansible_os_family == 'Darwin'

- name: Install OpenTofu on Linux
  include_tasks: linux.yml
  when: ansible_os_family in ['Debian', 'RedHat', 'Archlinux']

- name: Install OpenTofu on macOS
  include_tasks: macos.yml
  when: ansible_os_family == 'Darwin'

- name: Verify OpenTofu installation
  command: tofu --version
  register: tofu_version
  changed_when: false

- name: Display OpenTofu version
  debug:
    msg: "{{ tofu_version.stdout }}"

- name: Create OpenTofu configuration directory
  file:
    path: "{{ real_user_home }}/.tofu.d"
    state: directory
    mode: '0755'
  become: no
  become_user: "{{ real_user }}"

- name: Create Terraform compatibility directory (for legacy scripts)
  file:
    path: "{{ real_user_home }}/.terraform.d"
    state: directory
    mode: '0755'
  become: no
  become_user: "{{ real_user }}"

- name: Add OpenTofu aliases to shell profile
  blockinfile:
    path: "{{ real_user_home }}/.zshrc"
    marker: "# {mark} OPENTOFU ALIASES"
    block: |
      # OpenTofu aliases and functions
      alias tf='tofu'
      alias terraform='tofu'
      
      # OpenTofu helper functions
      tofu-init() {
        tofu init "$@"
      }
      
      tofu-plan() {
        tofu plan "$@"
      }
      
      tofu-apply() {
        tofu apply "$@"
      }
      
      tofu-destroy() {
        tofu destroy "$@"
      }
      
      tofu-fmt() {
        tofu fmt -recursive "$@"
      }
      
      tofu-validate() {
        tofu validate "$@"
      }
      
      tofu-workspace() {
        if [ -z "$1" ]; then
          tofu workspace list
        else
          tofu workspace select "$1"
        fi
      }
    create: yes
  become: no
  become_user: "{{ real_user }}"

- name: Add OpenTofu aliases to bash profile (fallback)
  blockinfile:
    path: "{{ real_user_home }}/.bashrc"
    marker: "# {mark} OPENTOFU ALIASES"
    block: |
      # OpenTofu aliases and functions
      alias tf='tofu'
      alias terraform='tofu'
      
      # OpenTofu helper functions
      tofu-init() {
        tofu init "$@"
      }
      
      tofu-plan() {
        tofu plan "$@"
      }
      
      tofu-apply() {
        tofu apply "$@"
      }
      
      tofu-destroy() {
        tofu destroy "$@"
      }
      
      tofu-fmt() {
        tofu fmt -recursive "$@"
      }
      
      tofu-validate() {
        tofu validate "$@"
      }
      
      tofu-workspace() {
        if [ -z "$1" ]; then
          tofu workspace list
        else
          tofu workspace select "$1"
        fi
      }
    create: yes
  become: no
  become_user: "{{ real_user }}"

- name: Display OpenTofu setup instructions
  debug:
    msg:
      - "OpenTofu has been installed successfully using the official installer!"
      - ""
      - "OpenTofu is a drop-in replacement for Terraform with the same commands:"
      - "  tofu init      # Initialize a new project"
      - "  tofu plan      # Plan your deployment"
      - "  tofu apply     # Apply your changes"
      - "  tofu destroy   # Destroy infrastructure"
      - ""
      - "Terraform compatibility:"
      - "  - 'terraform' command is aliased to 'tofu'"
      - "  - 'tf' is a short alias for 'tofu'"
      - "  - Helper functions: tofu-init, tofu-plan, tofu-apply, tofu-workspace"
      - ""
      - "Installation method: Official OpenTofu installer script"
      - "Binary location: /usr/local/bin/tofu"
      - ""
      - "Configuration directories:"
      - "  - {{ real_user_home }}/.tofu.d (OpenTofu config)"
      - "  - {{ real_user_home }}/.terraform.d (compatibility)"
      - ""
      - "To reload shell aliases: source ~/.zshrc"
      - "Documentation: https://opentofu.org/docs/"