- name: Development Environment Setup
  hosts: localhost
  connection: local
  gather_facts: yes
  become: no  # Don't become root by default

  vars:
    # Capture real user info before any privilege escalation
    real_user: "{{ ansible_env.USER }}"
    real_user_home: "{{ ansible_env.HOME }}"
    
    # Package installation flags
    install_docker: true
    install_vscode: true
    install_ohmyzsh: true
    install_neovim: true
    install_python_virtualenv: true
    install_obsidian: true
    install_pass: true
    install_opentofu: true
    install_awscli: true

  pre_tasks:
    - name: Display user information
      debug:
        msg: 
          - "Real User: {{ real_user }}"
          - "Real Home: {{ real_user_home }}"
          - "Operating System: {{ ansible_os_family }}"

  roles:
    - role: docker
      when: install_docker
      tags: docker
      become: yes  # Docker needs root

    - role: vscode
      when: install_vscode
      tags: vscode
      become: no  # VS Code installation needs root

    - role: ohmyzsh
      when: install_ohmyzsh
      tags: ohmyzsh
      vars:
        user_home: "{{ real_user_home }}"
        current_user: "{{ real_user }}"

    - role: neovim
      when: install_neovim
      tags: neovim
      become: yes  # Package installation needs root
      vars:
        user_home: "{{ real_user_home }}"
        current_user: "{{ real_user }}"

    - role: python_virtualenv
      when: install_python_virtualenv
      tags: python
      become: yes  # Package installation needs root
      vars:
        user_home: "{{ real_user_home }}"
        current_user: "{{ real_user }}"

    - role: obsidian
      when: install_obsidian
      tags: obsidian
      become: yes  # Package installation needs root

    - role: pass
      when: install_pass
      tags: pass
      become: yes  # Package installation needs root

    - role: opentofu
      when: install_opentofu
      tags: opentofu
      vars:
        user_home: "{{ real_user_home }}"
        current_user: "{{ real_user }}"

    - role: awscli
      when: install_awscli
      tags: awscli
      become: yes  # Installation needs root
      vars:
        user_home: "{{ real_user_home }}"
        current_user: "{{ real_user }}"