---
- name: Check if AWS CLI v2 is already installed
  command: aws --version
  register: aws_check
  failed_when: false
  changed_when: false

- name: Install AWS CLI v2 using official installer
  block:
    - name: Install unzip if not present
      package:
        name: unzip
        state: present
      become: yes

    - name: Detect system architecture
      set_fact:
        aws_arch: "{{ 'x86_64' if ansible_architecture == 'x86_64' else 'aarch64' if ansible_architecture == 'aarch64' else ansible_architecture }}"

    - name: Download AWS CLI v2 installer
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-{{ aws_arch }}.zip"
        dest: /tmp/awscliv2.zip
        mode: '0644'
        force: yes

    - name: Extract AWS CLI v2 installer
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Install AWS CLI v2
      command: /tmp/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
      become: yes

    - name: Clean up installer files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/awscliv2.zip
        - /tmp/aws
  when: 
    - aws_check.rc != 0 or 'aws-cli/2' not in aws_check.stderr

- name: Ensure AWS CLI binary is executable
  file:
    path: /usr/local/bin/aws
    mode: '0755'
  become: yes