---
- name: Check if Docker Desktop is installed
  stat:
    path: /Applications/Docker.app
  register: docker_app

- name: Install Docker Desktop via Homebrew Cask
  homebrew_cask:
    name: docker
    state: present
  when: not docker_app.stat.exists
